package com.gopiraj.Model;
// Generated Mar 26, 2017 11:06:23 AM by Hibernate Tools 3.6.0

/**
 * Aboutus generated by hbm2java
 */
public class Aboutus implements java.io.Serializable {

    private Integer aboutusId;
    private byte[] photograph;
    private String smallIntro;
    private Integer teachersNo;
    private Integer studentsNo;
    private Integer courseNo;
    private Integer citiesNo;

    public Aboutus() {
    }

    public Aboutus(byte[] photograph, String smallIntro, Integer teachersNo, Integer studentsNo, Integer courseNo, Integer citiesNo) {
        this.photograph = photograph;
        this.smallIntro = smallIntro;
        this.teachersNo = teachersNo;
        this.studentsNo = studentsNo;
        this.courseNo = courseNo;
        this.citiesNo = citiesNo;
    }

    public Integer getAboutusId() {
        return this.aboutusId;
    }

    public void setAboutusId(Integer aboutusId) {
        this.aboutusId = aboutusId;
    }

    public byte[] getPhotograph() {
        return this.photograph;
    }

    public void setPhotograph(byte[] photograph) {
        this.photograph = photograph;
    }

    public String getSmallIntro() {
        return this.smallIntro;
    }

    public void setSmallIntro(String smallIntro) {
        this.smallIntro = smallIntro;
    }

    public Integer getTeachersNo() {
        return this.teachersNo;
    }

    public void setTeachersNo(Integer teachersNo) {
        this.teachersNo = teachersNo;
    }

    public Integer getStudentsNo() {
        return this.studentsNo;
    }

    public void setStudentsNo(Integer studentsNo) {
        this.studentsNo = studentsNo;
    }

    public Integer getCourseNo() {
        return this.courseNo;
    }

    public void setCourseNo(Integer courseNo) {
        this.courseNo = courseNo;
    }

    public Integer getCitiesNo() {
        return this.citiesNo;
    }

    public void setCitiesNo(Integer citiesNo) {
        this.citiesNo = citiesNo;
    }

}
