package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private Integer activityId;
     private Person person;
     private String description;
     private Date creationTime;
     private byte[] attachment;

    public Activity() {
    }

    public Activity(Person person, String description, Date creationTime, byte[] attachment) {
       this.person = person;
       this.description = description;
       this.creationTime = creationTime;
       this.attachment = attachment;
    }
   
    public Integer getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public byte[] getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(byte[] attachment) {
        this.attachment = attachment;
    }




}


