package com.gopiraj.Model;
// Generated Feb 24, 2017 4:33:09 PM by Hibernate Tools 3.6.0



/**
 * BasicDetails generated by hbm2java
 */
public class BasicDetails  implements java.io.Serializable {


     private Integer basicDetailsId;
     private byte[] logo;
     private String name;
     private String email;
     private String mobileNo;
     private String phoneNo;
     private String emailId1;
     private String emailId2;
     private String address;
     private String quoteAboutCompany;

    public BasicDetails() {
    }

	
    public BasicDetails(String name, String email, String mobileNo, String phoneNo, String emailId1, String emailId2, String address, String quoteAboutCompany) {
        this.name = name;
        this.email = email;
        this.mobileNo = mobileNo;
        this.phoneNo = phoneNo;
        this.emailId1 = emailId1;
        this.emailId2 = emailId2;
        this.address = address;
        this.quoteAboutCompany = quoteAboutCompany;
    }
    public BasicDetails(byte[] logo, String name, String email, String mobileNo, String phoneNo, String emailId1, String emailId2, String address, String quoteAboutCompany) {
       this.logo = logo;
       this.name = name;
       this.email = email;
       this.mobileNo = mobileNo;
       this.phoneNo = phoneNo;
       this.emailId1 = emailId1;
       this.emailId2 = emailId2;
       this.address = address;
       this.quoteAboutCompany = quoteAboutCompany;
    }
   
    public Integer getBasicDetailsId() {
        return this.basicDetailsId;
    }
    
    public void setBasicDetailsId(Integer basicDetailsId) {
        this.basicDetailsId = basicDetailsId;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getEmailId1() {
        return this.emailId1;
    }
    
    public void setEmailId1(String emailId1) {
        this.emailId1 = emailId1;
    }
    public String getEmailId2() {
        return this.emailId2;
    }
    
    public void setEmailId2(String emailId2) {
        this.emailId2 = emailId2;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getQuoteAboutCompany() {
        return this.quoteAboutCompany;
    }
    
    public void setQuoteAboutCompany(String quoteAboutCompany) {
        this.quoteAboutCompany = quoteAboutCompany;
    }




}


