package com.gopiraj.Model;
// Generated Feb 24, 2017 9:51:20 PM by Hibernate Tools 3.6.0



/**
 * Corporates generated by hbm2java
 */
public class Corporates  implements java.io.Serializable {


     private Integer corporatesId;
     private String name;
     private String thought;
     private byte[] photograph;
     private String designation;

    public Corporates() {
    }

    public Corporates(String name, String thought, byte[] photograph, String designation) {
       this.name = name;
       this.thought = thought;
       this.photograph = photograph;
       this.designation = designation;
    }
   
    public Integer getCorporatesId() {
        return this.corporatesId;
    }
    
    public void setCorporatesId(Integer corporatesId) {
        this.corporatesId = corporatesId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getThought() {
        return this.thought;
    }
    
    public void setThought(String thought) {
        this.thought = thought;
    }
    public byte[] getPhotograph() {
        return this.photograph;
    }
    
    public void setPhotograph(byte[] photograph) {
        this.photograph = photograph;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }




}


