package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

    private Integer courseId;
    private OrganizationAdmin organizationAdmin;
    private String courseName;
    private int duration;
    private String description;
    //private Set enquiryCourses = new HashSet(0);

    public Course() {
    }

    public Course(OrganizationAdmin organizationAdmin, String courseName, int duration, String Description) {
        this.organizationAdmin = organizationAdmin;
        this.courseName = courseName;
        this.duration = duration;
        this.description = Description;
    }

    public Course(OrganizationAdmin organizationAdmin, String courseName, int duration, String Description, Set enquiryCourses) {
        this.organizationAdmin = organizationAdmin;
        this.courseName = courseName;
        this.duration = duration;
        this.description = Description;
//        this.enquiryCourses = enquiryCourses;
    }

    public Integer getCourseId() {
        return this.courseId;
    }

    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public OrganizationAdmin getOrganizationAdmin() {
        return this.organizationAdmin;
    }

    public void setOrganizationAdmin(OrganizationAdmin organizationAdmin) {
        this.organizationAdmin = organizationAdmin;
    }

    public String getCourseName() {
        return this.courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    public int getDuration() {
        return this.duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String Description) {
        this.description = Description;
    }

}
