package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer employeeId;
     Person person;
     private String password;
     private String position;
     private String accessLevel;
     private Set tasks = new HashSet(0);

    public Employee() {
    }

	
    public Employee(Person person, String password, String position, String accessLevel) {
        this.person = person;
        this.password = password;
        this.position = position;
        this.accessLevel = accessLevel;
    }
    public Employee(Person person, String password, String position, String accessLevel, Set tasks) {
       this.person = person;
       this.password = password;
       this.position = position;
       this.accessLevel = accessLevel;
       this.tasks = tasks;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getAccessLevel() {
        return this.accessLevel;
    }
    
    public void setAccessLevel(String accessLevel) {
        this.accessLevel = accessLevel;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


