package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enquiry generated by hbm2java
 */
public class Enquiry  implements java.io.Serializable {


     private Integer enqId;
     private String clgName;
     private String branch;
     private String semester;
     private String status;
     private String firstName;
     private String middleName;
     private String lastName;
     private String mailId;
     private Date dob;
     private String gender;
     private String streetAddress;
     private String city;
     private String state;
     private Date creationTime;
     private Set enquiryCourses = new HashSet(0);
     private Set enquiryContactnos = new HashSet(0);
     private Set sentMails = new HashSet(0);
     private Set sentSmses = new HashSet(0);

    public Enquiry() {
    }

	
    public Enquiry(String status, String firstName, String middleName, String lastName, String mailId, Date dob, String gender, String streetAddress, String city, String state) {
        this.status = status;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.mailId = mailId;
        this.dob = dob;
        this.gender = gender;
        this.streetAddress = streetAddress;
        this.city = city;
        this.state = state;
    }
    public Enquiry(String clgName, String branch, String semester, String status, String firstName, String middleName, String lastName, String mailId, Date dob, String gender, String streetAddress, String city, String state, Date creationTime, Set enquiryCourses, Set enquiryContactnos, Set sentMails, Set sentSmses) {
       this.clgName = clgName;
       this.branch = branch;
       this.semester = semester;
       this.status = status;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.mailId = mailId;
       this.dob = dob;
       this.gender = gender;
       this.streetAddress = streetAddress;
       this.city = city;
       this.state = state;
       this.creationTime = creationTime;
       this.enquiryCourses = enquiryCourses;
       this.enquiryContactnos = enquiryContactnos;
       this.sentMails = sentMails;
       this.sentSmses = sentSmses;
    }
   
    public Integer getEnqId() {
        return this.enqId;
    }
    
    public void setEnqId(Integer enqId) {
        this.enqId = enqId;
    }
    public String getClgName() {
        return this.clgName;
    }
    
    public void setClgName(String clgName) {
        this.clgName = clgName;
    }
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMailId() {
        return this.mailId;
    }
    
    public void setMailId(String mailId) {
        this.mailId = mailId;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getStreetAddress() {
        return this.streetAddress;
    }
    
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public Set getEnquiryCourses() {
        return this.enquiryCourses;
    }
    
    public void setEnquiryCourses(Set enquiryCourses) {
        this.enquiryCourses = enquiryCourses;
    }
    public Set getEnquiryContactnos() {
        return this.enquiryContactnos;
    }
    
    public void setEnquiryContactnos(Set enquiryContactnos) {
        this.enquiryContactnos = enquiryContactnos;
    }
    public Set getSentMails() {
        return this.sentMails;
    }
    
    public void setSentMails(Set sentMails) {
        this.sentMails = sentMails;
    }
    public Set getSentSmses() {
        return this.sentSmses;
    }
    
    public void setSentSmses(Set sentSmses) {
        this.sentSmses = sentSmses;
    }




}


