package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0

/**
 * EnquiryCourseId generated by hbm2java
 */
public class EnquiryCourseId implements java.io.Serializable {

    private int enquiryCourseId;
    private int enqCourseId;

    public EnquiryCourseId() {
    }

    public EnquiryCourseId(int enquiryCourseId, int enqCourseId) {
        this.enquiryCourseId = enquiryCourseId;
        this.enqCourseId = enqCourseId;
    }

    public int getEnquiryCourseId() {
        return this.enquiryCourseId;
    }

    public void setEnquiryCourseId(int enquiryCourseId) {
        this.enquiryCourseId = enquiryCourseId;
    }

    public int getEnqCourseId() {
        return this.enqCourseId;
    }

    public void setEnqCourseId(int enqCourseId) {
        this.enqCourseId = enqCourseId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof EnquiryCourseId)) {
            return false;
        }
        EnquiryCourseId castOther = (EnquiryCourseId) other;

        return (this.getEnquiryCourseId() == castOther.getEnquiryCourseId())
                && (this.getEnqCourseId() == castOther.getEnqCourseId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getEnquiryCourseId();
        result = 37 * result + this.getEnqCourseId();
        return result;
    }

}
