package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0

/**
 * EnquiryCourse generated by hbm2java
 */
public class EnquiryCourse implements java.io.Serializable {

    private EnquiryCourseId id;
    private Enquiry enquiry;
    private Course course;

    public EnquiryCourse() {
    }

    public EnquiryCourse(EnquiryCourseId id, Enquiry enquiry, Course course) {
        this.id = id;
        this.enquiry = enquiry;
        this.course = course;
    }

    public EnquiryCourseId getId() {
        return this.id;
    }

    public void setId(EnquiryCourseId id) {
        this.id = id;
    }

    public Enquiry getEnquiry() {
        return this.enquiry;
    }

    public void setEnquiry(Enquiry enquiry) {
        this.enquiry = enquiry;
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

}
