package com.gopiraj.Model;
// Generated Jan 17, 2017 4:15:14 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * MenuMaster generated by hbm2java
 */
public class MenuMaster implements java.io.Serializable {

    private Integer menuMasterId;
    private String menuName;
    private String pageName;
    private Set menuTypes = new HashSet(0);
    private Set subMenuTypes = new HashSet(0);

    public MenuMaster() {
    }

    public MenuMaster(String menuName, String pageName) {
        this.menuName = menuName;
        this.pageName = pageName;
    }

    public MenuMaster(String menuName, String pageName, Set menuTypes, Set subMenuTypes) {
        this.menuName = menuName;
        this.pageName = pageName;
        this.menuTypes = menuTypes;
        this.subMenuTypes = subMenuTypes;
    }

    public Integer getMenuMasterId() {
        return this.menuMasterId;
    }

    public void setMenuMasterId(Integer menuMasterId) {
        this.menuMasterId = menuMasterId;
    }

    public String getMenuName() {
        return this.menuName;
    }

    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public String getPageName() {
        return this.pageName;
    }

    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    public Set getMenuTypes() {
        return this.menuTypes;
    }

    public void setMenuTypes(Set menuTypes) {
        this.menuTypes = menuTypes;
    }

    public Set getSubMenuTypes() {
        return subMenuTypes;
    }

    public void setSubMenuTypes(Set subMenuTypes) {
        this.subMenuTypes = subMenuTypes;
    }

}
