package com.gopiraj.Model;
// Generated Jan 17, 2017 4:15:14 PM by Hibernate Tools 3.6.0

/**
 * MenuType generated by hbm2java
 */
public class MenuType implements java.io.Serializable {

    private Integer menuTypeId;
    private MenuMaster menuMaster;
    private String personType;

    public MenuType() {
    }

    public MenuType(MenuMaster menuMaster, String personType) {
        this.menuMaster = menuMaster;
        this.personType = personType;
    }

    public Integer getMenuTypeId() {
        return this.menuTypeId;
    }

    public void setMenuTypeId(Integer menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    public MenuMaster getMenuMaster() {
        return this.menuMaster;
    }

    public void setMenuMaster(MenuMaster menuMaster) {
        this.menuMaster = menuMaster;
    }

    public String getPersonType() {
        return this.personType;
    }

    public void setPersonType(String personType) {
        this.personType = personType;
    }

}
