package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * OrganizationAdmin generated by hbm2java
 */
public class OrganizationAdmin  implements java.io.Serializable {


     private Integer organizationAdmin;
     private Person person;
     private String password;
     private Set courses = new HashSet(0);
     private Set tasks = new HashSet(0);
     private Set preBrochureses = new HashSet(0);
     private Set reports = new HashSet(0);

    public OrganizationAdmin() {
    }

	
    public OrganizationAdmin(Person person, String password) {
        this.person = person;
        this.password = password;
    }
    public OrganizationAdmin(Person person, String password, Set courses, Set tasks, Set preBrochureses, Set reports) {
       this.person = person;
       this.password = password;
       this.courses = courses;
       this.tasks = tasks;
       this.preBrochureses = preBrochureses;
       this.reports = reports;
    }
   
    public Integer getOrganizationAdmin() {
        return this.organizationAdmin;
    }
    
    public void setOrganizationAdmin(Integer organizationAdmin) {
        this.organizationAdmin = organizationAdmin;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }
    public Set getPreBrochureses() {
        return this.preBrochureses;
    }
    
    public void setPreBrochureses(Set preBrochureses) {
        this.preBrochureses = preBrochureses;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }




}


