package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer personId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String mailId;
     private Date dateOfBirth;
     private Date creationTime;
     private String streetAdd;
     private String city;
     private String state;
     private String gender;
     private String personType;
     private Set activities = new HashSet(0);
     private Set personContactnos = new HashSet(0);
     private OrganizationAdmin organizationAdmin;
     private Set sentMails = new HashSet(0);
     private Employee employee;
     private Set feedbacks = new HashSet(0);
     private Set sentSmses = new HashSet(0);
     

    public Person() {
    }

	
    public Person(String firstName, String middleName, String lastName, String mailId, Date dateOfBirth, Date creationTime, String streetAdd, String city, String state, String gender, String personType) {
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.mailId = mailId;
        this.dateOfBirth = dateOfBirth;
        this.creationTime = creationTime;
        this.streetAdd = streetAdd;
        this.city = city;
        this.state = state;
        this.gender = gender;
        this.personType = personType;
    }
    public Person(String firstName, String middleName, String lastName, String mailId, Date dateOfBirth, Date creationTime, String streetAdd, String city, String state, String gender, String personType, Set activities, Set personContactnos, OrganizationAdmin organizationAdmin, Set sentMails, Employee employee, Set feedbacks, Set sentSmses) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.mailId = mailId;
       this.dateOfBirth = dateOfBirth;
       this.creationTime = creationTime;
       this.streetAdd = streetAdd;
       this.city = city;
       this.state = state;
       this.gender = gender;
       this.personType = personType;
       this.activities = activities;
       this.personContactnos = personContactnos;
       this.organizationAdmin = organizationAdmin;
       this.sentMails = sentMails;
       this.employee = employee;
       this.feedbacks = feedbacks;
       this.sentSmses = sentSmses;
       
    }
   
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMailId() {
        return this.mailId;
    }
    
    public void setMailId(String mailId) {
        this.mailId = mailId;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
    public String getStreetAdd() {
        return this.streetAdd;
    }
    
    public void setStreetAdd(String streetAdd) {
        this.streetAdd = streetAdd;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPersonType() {
        return this.personType;
    }
    
    public void setPersonType(String personType) {
        this.personType = personType;
    }
    public Set getActivities() {
        return this.activities;
    }
    
    public void setActivities(Set activities) {
        this.activities = activities;
    }
    public Set getPersonContactnos() {
        return this.personContactnos;
    }
    
    public void setPersonContactnos(Set personContactnos) {
        this.personContactnos = personContactnos;
    }
    public OrganizationAdmin getOrganizationAdmin() {
        return this.organizationAdmin;
    }
    
    public void setOrganizationAdmin(OrganizationAdmin organizationAdmin) {
        this.organizationAdmin = organizationAdmin;
    }
    public Set getSentMails() {
        return this.sentMails;
    }
    
    public void setSentMails(Set sentMails) {
        this.sentMails = sentMails;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Set getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set getSentSmses() {
        return this.sentSmses;
    }
    
    public void setSentSmses(Set sentSmses) {
        this.sentSmses = sentSmses;
    }

  
}

