package com.gopiraj.Model;
// Generated Feb 26, 2017 12:45:46 PM by Hibernate Tools 3.6.0



/**
 * PersonType generated by hbm2java
 */
public class PersonType  implements java.io.Serializable {


     private Integer personTypeId;
     private String personTypeName;

    public PersonType() {
    }

    public PersonType(String personTypeName) {
       this.personTypeName = personTypeName;
    }
   
    public Integer getPersonTypeId() {
        return this.personTypeId;
    }
    
    public void setPersonTypeId(Integer personTypeId) {
        this.personTypeId = personTypeId;
    }
    public String getPersonTypeName() {
        return this.personTypeName;
    }
    
    public void setPersonTypeName(String personTypeName) {
        this.personTypeName = personTypeName;
    }




}


