package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PreBrochures generated by hbm2java
 */
public class PreBrochures  implements java.io.Serializable {


     private Integer preBrochuresId;
     private OrganizationAdmin organizationAdmin;
     private String title;
     private byte[] upload;
     private Set sentMails = new HashSet(0);

    public PreBrochures() {
    }

	
    public PreBrochures(OrganizationAdmin organizationAdmin, String title, byte[] upload) {
        this.organizationAdmin = organizationAdmin;
        this.title = title;
        this.upload = upload;
    }
    public PreBrochures(OrganizationAdmin organizationAdmin, String title, byte[] upload, Set sentMails) {
       this.organizationAdmin = organizationAdmin;
       this.title = title;
       this.upload = upload;
       this.sentMails = sentMails;
    }
   
    public Integer getPreBrochuresId() {
        return this.preBrochuresId;
    }
    
    public void setPreBrochuresId(Integer preBrochuresId) {
        this.preBrochuresId = preBrochuresId;
    }
    public OrganizationAdmin getOrganizationAdmin() {
        return this.organizationAdmin;
    }
    
    public void setOrganizationAdmin(OrganizationAdmin organizationAdmin) {
        this.organizationAdmin = organizationAdmin;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public byte[] getUpload() {
        return this.upload;
    }
    
    public void setUpload(byte[] upload) {
        this.upload = upload;
    }
    public Set getSentMails() {
        return this.sentMails;
    }
    
    public void setSentMails(Set sentMails) {
        this.sentMails = sentMails;
    }




}


