package com.gopiraj.Model;
// Generated Sep 19, 2016 6:34:26 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * SentMail generated by hbm2java
 */
public class SentMail  implements java.io.Serializable {


     private Integer sentMailId;
     private PreBrochures preBrochures;
     private Enquiry enquiry;
     private Person person;
     private PreText preText;
     private Date creationTime;

    public SentMail() {
    }

    public SentMail(PreBrochures preBrochures, Enquiry enquiry, Person person, PreText preText, Date creationTime) {
       this.preBrochures = preBrochures;
       this.enquiry = enquiry;
       this.person = person;
       this.preText = preText;
       this.creationTime = creationTime;
    }
   
    public Integer getSentMailId() {
        return this.sentMailId;
    }
    
    public void setSentMailId(Integer sentMailId) {
        this.sentMailId = sentMailId;
    }
    public PreBrochures getPreBrochures() {
        return this.preBrochures;
    }
    
    public void setPreBrochures(PreBrochures preBrochures) {
        this.preBrochures = preBrochures;
    }
    public Enquiry getEnquiry() {
        return this.enquiry;
    }
    
    public void setEnquiry(Enquiry enquiry) {
        this.enquiry = enquiry;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public PreText getPreText() {
        return this.preText;
    }
    
    public void setPreText(PreText preText) {
        this.preText = preText;
    }
    public Date getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }




}


