package com.gopiraj.Model;
// Generated Mar 26, 2017 11:06:23 AM by Hibernate Tools 3.6.0

/**
 * SliderImage generated by hbm2java
 */
public class SliderImage implements java.io.Serializable {

    private Integer sliderImageId;
    private byte[] image;
    private String description;

    public SliderImage() {
    }

    public SliderImage(byte[] image, String description) {
        this.image = image;
        this.description = description;
    }

    public Integer getSliderImageId() {
        return this.sliderImageId;
    }

    public void setSliderImageId(Integer sliderImageId) {
        this.sliderImageId = sliderImageId;
    }

    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
