package com.gopiraj.Model;
// Generated Feb 24, 2017 9:51:20 PM by Hibernate Tools 3.6.0



/**
 * Teachers generated by hbm2java
 */
public class Teachers  implements java.io.Serializable {


     private Integer teachersId;
     private String name;
     private String thought;
     private byte[] photograph;
     private String designation;
     private String facebook;
     private String gmail;
     private String twitter;

    public Teachers() {
    }

    public Teachers(String name, String thought, byte[] photograph, String designation, String facebook, String gmail, String twitter) {
       this.name = name;
       this.thought = thought;
       this.photograph = photograph;
       this.designation = designation;
       this.facebook = facebook;
       this.gmail = gmail;
       this.twitter = twitter;
    }
   
    public Integer getTeachersId() {
        return this.teachersId;
    }
    
    public void setTeachersId(Integer teachersId) {
        this.teachersId = teachersId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getThought() {
        return this.thought;
    }
    
    public void setThought(String thought) {
        this.thought = thought;
    }
    public byte[] getPhotograph() {
        return this.photograph;
    }
    
    public void setPhotograph(byte[] photograph) {
        this.photograph = photograph;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getGmail() {
        return this.gmail;
    }
    
    public void setGmail(String gmail) {
        this.gmail = gmail;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }




}


